### PR TITLE
resposiveness fix initial: post list items.

### PR DESCRIPTION
**Pull request by JaheimPrice**
image
image
image
image

### CODE REVIEW

**Comment by JaheimPrice** [comment]
Closed because don't want it to targeted towards the original's master branch, want it to be a different branch just in case.

**Comment by JaheimPrice** [comment]
It may not be as precise as original and may require some tweaking, but would this be close to what'd you like?

**Comment by TeisybeLT** [comment]
Yeah, this looks about right. Not too picky about pixel-level alignment. Could you please move your code to one of the `.scss` files, because adding an extra stylesheet while already having scss support seems excessive. Maybe `_list.scss` (https://github.com/LordMathis/hugo-theme-nightfall/blob/main/assets/sass/pages/_list.scss). It seems like an appropriate place.

**Comment by JaheimPrice** [comment]
> Yeah, this looks about right. Not too picky about pixel-level alignment. Could you please move your code to one of the `.scss` files, because adding an extra stylesheet while already having scss support seems excessive. Maybe `_list.scss` (https://github.com/LordMathis/hugo-theme-nightfall/blob/main/assets/sass/pages/_list.scss). It seems like an appropriate place.

Sure thing, seems straightforward! Attempting now.

**Pull request merged**
